=== buddycloud/buddycloud-xep/xmpp/registrar/ns.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!-- DTD for registered namespaces -->
<!ELEMENT registry ( meta, ns* ) >
<!ELEMENT meta ( title, legal, overview, revision+ ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT legal (#PCDATA)* >
<!ELEMENT overview (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark (#PCDATA)* >
<!ELEMENT ns ( name, doc ) >
<!ELEMENT name (#PCDATA)* >
<!ELEMENT doc (#PCDATA)* >

=== buddycloud/buddycloud-xep/xmpp/registrar/namespaces.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE registry SYSTEM 'ns.dtd' [
  <!ENTITY % ents SYSTEM 'reg.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='ns.xsl'?>
<registry>
  <meta>
    <title>Jabber/XMPP Protocol Namespaces</title>
    &LEGALNOTICE;
    <overview>This is the official registry of Jabber/XMPP protocol namespaces as maintained by the &REGISTRAR;. This registry contains only namespaces that are defined in the <link url='/specs/'>XMPP RFCs</link> (published by the <link url='http://www.ietf.org/'>IETF</link>) or in <link url='/extensions/'>XMPP Extension Protocols</link> that have advanced to a status of Active, Draft, or Final within the standards process of the <link url='/xsf/'>XMPP Standards Foundation</link>. Other namespaces may be in use within the Jabber/XMPP community, but are not added to this page until the relevant document meets the above criteria.</overview>
    <revision>
      <version>0.38</version>
      <date>2010-03-13</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:pie:0 from XEP-0227.</remark>
    </revision>
    <revision>
      <version>0.37</version>
      <date>2009-06-25</date>
      <initials>psa</initials>
      <remark>Added jabber:x:conference from XEP-0249.</remark>
    </revision>
    <revision>
      <version>0.36</version>
      <date>2009-06-17</date>
      <initials>psa</initials>
      <remark>Added stream management namespace from XEP-0198.</remark>
    </revision>
    <revision>
      <version>0.35</version>
      <date>2009-06-10</date>
      <initials>psa</initials>
      <remark>Added Jingle namespaces from XEP-0166, XEP-0167, XEP-0176, and XEP-0177.</remark>
    </revision>
    <revision>
      <version>0.34</version>
      <date>2008-11-13</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:attention:0 from XEP-0224.</remark>
    </revision>
    <revision>
      <version>0.33</version>
      <date>2008-09-03</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:bob from XEP-0231, urn:xmpp:media-element from XEP-0221, and urn:xmpp:captcha from XEP-0158.</remark>
    </revision>
    <revision>
      <version>0.32</version>
      <date>2008-07-16</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:archive from XEP-0136.</remark>
    </revision>
    <revision>
      <version>0.31</version>
      <date>2008-05-09</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:langtrans and urn:xmpp:langtrans#items from XEP-0171.</remark>
    </revision>
    <revision>
      <version>0.30</version>
      <date>2008-03-05</date>
      <initials>psa</initials>
      <remark>Changed http://jabber.org/protoco/errors to urn:xmpp:errors per version 1.1. of XEP-0182.</remark>
    </revision>
    <revision>
      <version>0.29</version>
      <date>2007-11-07</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:avatar:data and urn:xmpp:avatar:metadata (XEP-0084).</remark>
    </revision>
    <revision>
      <version>0.28</version>
      <date>2007-09-26</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:receipts (XEP-0184).</remark>
    </revision>
    <revision>
      <version>0.27</version>
      <date>2007-06-12</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:ping (XEP-0199).</remark>
    </revision>
    <revision>
      <version>0.26</version>
      <date>2007-03-29</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:delay (XEP-0203).</remark>
    </revision>
    <revision>
      <version>0.25</version>
      <date>2007-03-28</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:time (XEP-0202).</remark>
    </revision>
    <revision>
      <version>0.24</version>
      <date>2007-03-15</date>
      <initials>psa</initials>
      <remark>Modified XEP-0155 namespace.</remark>
    </revision>
    <revision>
      <version>0.23</version>
      <date>2007-02-28</date>
      <initials>psa</initials>
      <remark>Added XMPP over BOSH (XEP-0206).</remark>
    </revision>
    <revision>
      <version>0.22</version>
      <date>2007-01-17</date>
      <initials>psa</initials>
      <remark>Added chat session negotiation (XEP-0155).</remark>
    </revision>
    <revision>
      <version>0.21</version>
      <date>2006-09-20</date>
      <initials>psa</initials>
      <remark>Added result set management (XEP-0059).</remark>
    </revision>
    <revision>
      <version>0.20</version>
      <date>2006-08-16</date>
      <initials>psa</initials>
      <remark>Added vcard-temp:x:update (XEP-0153).</remark>
    </revision>
    <revision>
      <version>0.19</version>
      <date>2006-07-05</date>
      <initials>psa</initials>
      <remark>Corrected pubsub registration.</remark>
    </revision>
    <revision>
      <version>0.18</version>
      <date>2006-06-05</date>
      <initials>psa</initials>
      <remark>Added nick (XEP-0172).</remark>
    </revision>
    <revision>
      <version>0.17</version>
      <date>2006-05-16</date>
      <initials>psa</initials>
      <remark>Added errors (XEP-0182).</remark>
    </revision>
    <revision>
      <version>0.16</version>
      <date>2005-12-14</date>
      <initials>psa</initials>
      <remark>Added http-auth (XEP-0070) as well as soap and soap#fault (XEP-0072).</remark>
    </revision>
    <revision>
      <version>0.15</version>
      <date>2005-10-05</date>
      <initials>psa</initials>
      <remark>Added iq-gateway (XEP-0100).</remark>
    </revision>
    <revision>
      <version>0.14</version>
      <date>2005-08-26</date>
      <initials>psa</initials>
      <remark>Added chatstates (XEP-0085), waitinglist (XEP-0130), sipub (XEP-0137), and rosterx (XEP-0144).</remark>
    </revision>
    <revision>
      <version>0.13</version>
      <date>2005-06-16</date>
      <initials>psa</initials>
      <remark>Added compression (XEP-0138).</remark>
    </revision>
    <revision>
      <version>0.12</version>
      <date>2005-05-12</date>
      <initials>psa</initials>
      <remark>Added xdata-layout (XEP-0141).</remark>
    </revision>
    <revision>
      <version>0.11</version>
      <date>2005-03-03</date>
      <initials>psa</initials>
      <remark>Added httpbind (XEP-0124).</remark>
    </revision>
    <revision>
      <version>0.10</version>
      <date>2004-11-12</date>
      <initials>psa</initials>
      <remark>Added tune (XEP-0118).</remark>
    </revision>
    <revision>
      <version>0.10</version>
      <date>2004-10-27</date>
      <initials>psa</initials>
      <remark>Added urn:ietf:* namespaces from XMPP RFCs.</remark>
    </revision>
    <revision>
      <version>0.9</version>
      <date>2004-10-20</date>
      <initials>psa</initials>
      <remark>Added mood (XEP-0107) and activity (XEP-0108).</remark>
    </revision>
    <revision>
      <version>0.8</version>
      <date>2004-10-12</date>
      <initials>psa</initials>
      <remark>Added geoloc (XEP-0080) and physloc (XEP-0112).</remark>
    </revision>
    <revision>
      <version>0.7</version>
      <date>2004-10-11</date>
      <initials>psa</initials>
      <remark>Added XHTML-IM (XEP-0071), advanced message processing (XEP-0079), and nested roster groups (XEP-0083).</remark>
    </revision>
    <revision>
      <version>0.6</version>
      <date>2004-09-22</date>
      <initials>psa</initials>
      <remark>Added data forms validation (XEP-0122).</remark>
    </revision>
    <revision>
      <version>0.5</version>
      <date>2004-08-02</date>
      <initials>psa</initials>
      <remark>Added entity capabilities (XEP-0115).</remark>
    </revision>
    <revision>
      <version>0.4</version>
      <date>2004-05-10</date>
      <initials>psa</initials>
      <remark>Added extended stanza addressing (XEP-0033).</remark>
    </revision>
    <revision>
      <version>0.3</version>
      <date>2003-12-10</date>
      <initials>psa</initials>
      <remark>Added pubsub and ibb (XEP-0060 and XEP-0047).</remark>
    </revision>
    <revision>
      <version>0.2</version>
      <date>2003-10-08</date>
      <initials>psa</initials>
      <remark>Added various "historical" namespaces.</remark>
    </revision>
    <revision>
      <version>0.1</version>
      <date>2003-09-09</date>
      <initials>psa</initials>
      <remark>Initial version.</remark>
    </revision>
  </meta>
  <!-- new-style HTTP URIs at jabber.org -->
  <ns>
    <name>http://jabber.org/protocol/activity</name>
    <doc>&xep0108;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/address</name>
    <doc>&xep0033;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/amp</name>
    <doc>&xep0079;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/amp#errors</name>
    <doc>&xep0079;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/bytestreams</name>
    <doc>&xep0065;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/caps</name>
    <doc>&xep0115;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/chatstates</name>
    <doc>&xep0085;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/commands</name>
    <doc>&xep0050;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/compress</name>
    <doc>&xep0138;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/disco#info</name>
    <doc>&xep0030;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/disco#items</name>
    <doc>&xep0030;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/feature-neg</name>
    <doc>&xep0020;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/geoloc</name>
    <doc>&xep0080;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/http-auth</name>
    <doc>&xep0070;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/httpbind</name>
    <doc>&xep0124;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/ibb</name>
    <doc>&xep0047;</doc>
  </ns>
  <ns>
    <name>http://jabber.org/protocol/mood</name>
    <doc>&xep0107;</doc>
  </ns>
  <ns>
