=== buddycloud/buddycloud-xep/xmpp/registrar/vars.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!-- DTD for disco feature vars -->
<!ELEMENT registry ( meta, var* ) >
<!ELEMENT meta ( title, legal, overview, revision+ ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT legal (#PCDATA)* >
<!ELEMENT overview (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark (#PCDATA)* >
<!ELEMENT var ( name, desc, doc ) >
<!ELEMENT name (#PCDATA)* >
<!ELEMENT desc (#PCDATA)* >
<!ELEMENT doc (#PCDATA)* >

=== buddycloud/buddycloud-xep/xmpp/registrar/disco-features.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE registry SYSTEM 'vars.dtd' [
  <!ENTITY % ents SYSTEM "reg.ent">
%ents;
]>
<?xml-stylesheet type='text/xsl' href='vars.xsl'?>
<registry>
  <meta>
    <title>Service Discovery Features</title>
    &LEGALNOTICE;
    <overview>The 'var' attribute of the &lt;feature/&gt; element within the 'http://jabber.org/protocol/disco#info' namespace may contain any namespace that is registered with the &REGISTRAR; (see &lt;<link url='http://www.xmpp.org/registrar/namespaces.html'>http://www.xmpp.org/registrar/namespaces.html</link>&gt;) as well as some additional values that have been separately registered with the Registrar.</overview>
    <revision>
      <version>0.19</version>
      <date>2010-03-15</date>
      <initials>psa</initials>
      <remark>Added missing feature http://jabber.org/protocol/bytestreams#udp from XEP-0065.</remark>
    </revision>
    <revision>
      <version>0.18</version>
      <date>2009-06-10</date>
      <initials>psa</initials>
      <remark>Added urn:xmpp:jingle:apps:rtp:audio and urn:xmpp:jingle:apps:rtp:video from XEP-0167; added urn:ietf:rfc:3264 from XEP-0176.</remark>
    </revision>
    <revision>
      <version>0.17</version>
      <date>2009-04-01</date>
      <initials>psa</initials>
      <remark>Deleted disco#publish, which was removed from XEP-0030.</remark>
    </revision>
    <revision>
      <version>0.16</version>
      <date>2008-07-16</date>
      <initials>psa</initials>
      <remark>Added archiving features from XEP-0136.</remark>
    </revision>
    <revision>
      <version>0.15</version>
      <date>2007-11-07</date>
      <initials>psa</initials>
      <remark>Added avatar features from XEP-0084.</remark>
    </revision>
    <revision>
      <version>0.14</version>
      <date>2007-09-27</date>
      <initials>psa</initials>
      <remark>Added ping from XEP-0199 (belatedly) and receipts from XEP-0184; also updated pubsub features per version 1.10 of XEP-0060.</remark>
    </revision>
    <revision>
      <version>0.13</version>
      <date>2007-03-29</date>
      <initials>psa</initials>
      <remark>Added delayed delivery from XEP-0203.</remark>
    </revision>
    <revision>
      <version>0.12</version>
      <date>2007-03-28</date>
      <initials>psa</initials>
      <remark>Added entity time from XEP-0202.</remark>
    </revision>
    <revision>
      <version>0.11</version>
      <date>2007-01-17</date>
      <initials>psa</initials>
      <remark>Added chat session negotiation feature from XEP-0155.</remark>
    </revision>
    <revision>
      <version>0.10</version>
      <date>2006-07-05</date>
      <initials>psa</initials>
      <remark>Corrected pubsub registration.</remark>
    </revision>
    <revision>
      <version>0.9</version>
      <date>2006-01-24</date>
      <initials>psa</initials>
      <remark>Added all registered namespaces to reduce confusion; added reference to XEP-0160 for msgoffline feature.</remark>
    </revision>
    <revision>
      <version>0.8</version>
      <date>2005-08-26</date>
      <initials>psa</initials>
      <remark>Added waiting list scheme features from XEP-0130.</remark>
    </revision>
    <revision>
      <version>0.7</version>
      <date>2005-05-12</date>
      <initials>psa</initials>
      <remark>Added jid\20escaping [sic] feature from XEP-0106.</remark>
    </revision>
    <revision>
      <version>0.6</version>
      <date>2005-01-18</date>
      <initials>psa</initials>
      <remark>Added missing features from XEP-0045.</remark>
    </revision>
    <revision>
      <version>0.5</version>
      <date>2004-12-03</date>
      <initials>psa</initials>
      <remark>Added numerous publish-subscribe features from XEP-0060.</remark>
    </revision>
    <revision>
      <version>0.4</version>
      <date>2004-11-02</date>
      <initials>psa</initials>
      <remark>Added a number of non-namespace features per Standards list discussion.</remark>
    </revision>
    <revision>
      <version>0.3</version>
      <date>2004-10-11</date>
      <initials>psa</initials>
      <remark>Added XEP-0079 features.</remark>
    </revision>
    <revision>
      <version>0.2</version>
      <date>2003-05-08</date>
      <initials>psa</initials>
      <remark>Major overhaul, new format.</remark>
    </revision>
    <revision>
      <version>0.1</version>
      <date>2003-04-23</date>
      <initials>psa</initials>
      <remark>Initial version (parameters from XEP-0030).</remark>
    </revision>
  </meta>
  <var>
    <name>dnssrv</name>
    <desc>Support for DNS SRV lookups of XMPP services.</desc>
    <doc>&xmppcore;, &xmppim;</doc>
  </var>
  <var>
    <name>fullunicode</name>
    <desc>Support for Unicode characters, including in displayed text, JIDs, and passwords.</desc>
    <doc>N/A</doc>
  </var>
  <var>
    <name>gc-1.0</name>
    <desc>Support for the "groupchat 1.0" protocol.</desc>
    <doc>&xep0045;</doc>
  </var>
  <!-- HTTP URIs at jabber.org -->
  <var>
    <name>http://jabber.org/protocol/activity</name>
    <desc>See XEP-0108</desc>
    <doc>&xep0108;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/address</name>
    <desc>See XEP-0033</desc>
    <doc>&xep0033;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp</name>
    <desc>See XEP-0079</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp#errors</name>
    <desc>See XEP-0079</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?action=alert</name>
    <desc>Support for the "alert" action in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?action=drop</name>
    <desc>Support for the "drop" action in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?action=error</name>
    <desc>Support for the "error" action in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?action=notify</name>
    <desc>Support for the "notify" action in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?condition=deliver</name>
    <desc>Support for the "deliver" condition in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?condition=expire-at</name>
    <desc>Support for the "expire-at" condition in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/amp?condition=match-resource</name>
    <desc>Support for the "match-resource" condition in Advanced Message Processing.</desc>
    <doc>&xep0079;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/bytestreams</name>
    <desc>See XEP-0065</desc>
    <doc>&xep0065;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/bytestreams#udp</name>
    <desc>See XEP-0065</desc>
    <doc>&xep0065;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/caps</name>
    <desc>See XEP-0115</desc>
    <doc>&xep0115;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/chatstates</name>
    <desc>See XEP-0085</desc>
    <doc>&xep0085;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/commands</name>
    <desc>See XEP-0050</desc>
    <doc>&xep0050;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/compress</name>
    <desc>See XEP-0138</desc>
    <doc>&xep0138;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/disco#info</name>
    <desc>See XEP-0030</desc>
    <doc>&xep0030;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/disco#items</name>
    <desc>See XEP-0030</desc>
    <doc>&xep0030;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/feature-neg</name>
    <desc>See XEP-0020</desc>
    <doc>&xep0020;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/geoloc</name>
    <desc>See XEP-0080</desc>
    <doc>&xep0080;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/http-auth</name>
    <desc>See XEP-0072</desc>
    <doc>&xep0072;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/httpbind</name>
    <desc>See XEP-0124</desc>
    <doc>&xep0124;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/ibb</name>
    <desc>See XEP-0047</desc>
    <doc>&xep0047;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/mood</name>
    <desc>See XEP-0107</desc>
    <doc>&xep0107;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc</name>
    <desc>See XEP-0045</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#admin</name>
    <desc>See XEP-0045</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#owner</name>
    <desc>See XEP-0045</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#register</name>
    <desc>Support for the muc#register FORM_TYPE in Multi-User Chat.</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#roomconfig</name>
    <desc>Support for the muc#roomconfig FORM_TYPE in Multi-User Chat.</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#roominfo</name>
    <desc>Support for the muc#roominfo FORM_TYPE in Multi-User Chat.</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/muc#user</name>
    <desc>See XEP-0045</desc>
    <doc>&xep0045;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/offline</name>
    <desc>See XEP-0013</desc>
    <doc>&xep0013;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/physloc</name>
    <desc>DEPRECATED</desc>
    <doc>&xep0080;</doc>
  </var>
  <var>
    <name>http://jabber.org/protocol/pubsub#access-authorize</name>
    <desc>The default node access model is authorize.</desc>
